### ISSUE TITLE
Throw exception: cannot convert circular structure to JSON

### ISSUE THREAD

**Issue by webbery** [vytenisu/npm-dts#31]
Hi~
I meet this issue in version 1.3.11. 
```
[npm-dts] [debug] : tsc --declaration --emitDeclarationOnly --declarationDir "/tmp/tmp-23771-4LL8PXNbafX4/npm-dts"
[npm-dts] [error] : Generation of index.d.ts has failed!
(node:23771) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Error'
    --- property 'error' closes the circle
    at JSON.stringify (<anonymous>)
    at t.showDebugError (/home/ywb/test/civet-extension/node_modules/npm-dts/dist/webpack:/npm-dts/lib/generator.ts:165:32)
    at t.<anonymous> (/home/ywb/test/civet-extension/node_modules/npm-dts/dist/webpack:/npm-dts/lib/generator.ts:117:14)
    at /home/ywb/test/civet-extension/node_modules/npm-dts/dist/index.js:1:4093
    at Object.next (/home/ywb/test/civet-extension/node_modules/npm-dts/dist/index.js:1:4198)
    at /home/ywb/test/civet-extension/node_modules/npm-dts/dist/index.js:1:3110
    at new Promise (<anonymous>)
    at i (/home/ywb/test/civet-extension/node_modules/npm-dts/dist/index.js:1:2855)
    at /home/ywb/test/civet-extension/node_modules/npm-dts/dist/webpack:/npm-dts/lib/generator.ts:111:43
```
I use `npm-dts-webpack-plugin` to pass original options to `npm-dts`. Here is my options:
```
{
  entry: 'src/civet.ts',
  root: path.resolve(process.cwd() + 'src')
}
```
and my source code structure as follows:
```
root
  |-- src
      |-- civet.ts
      |-- protocal.ts
  |-- package.json
  |-- webpack.config.js
```
I didn't know why it throw exception. How to fix it?

**Comment by webbery** [comment]
After I add '/' before 'src'.
```
{
      entry: 'src/civet.ts',
      root: path.resolve(process.cwd() + '/src'),
      logLevel: 'debug'
    }
```
It still find `civet.ts` in root path:
```
npm-dts] [debug] : tsc --declaration --emitDeclarationOnly --declarationDir "/tmp/tmp-903-7R6B9HRuV8Dq/npm-dts"
[npm-dts] [error] : Generation of index.d.ts has failed!
[npm-dts] [debug] : Error: 
error TS6053: File '/home/ywb/test/civet-extension/civet.ts' not found.
  The file is in the program because:
    Part of 'files' list in tsconfig.json
error TS6053: File '/home/ywb/test/civet-extension/src/**/*.ts' not found.
  The file is in the program because:
    Part of 'files' list in tsconfig.json

[npm-dts] [info] : If issue is not severe, you can try forcing execution using force flag.
[npm-dts] [info] : In case of command line usage, add "-f" as the first parameter.
```
Should I must put `src/civet.ts` to root directory? What's the difference between `root` and `entry`?
